debug: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: auth_user
    password: auth_password
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.UUIDSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://localhost:9091
        auto.register.schema: false
        use.latest.version: true
        schema.reflection: true
        value.subject.name.strategy: io.confluent.kafka.serializers.subject.RecordNameStrategy

  flyway:
    locations: db/migration
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: /
#          jwk-set-uri: /oauth2/jwks
#          audiences: auth-client

event:
  user:
    streaming: users.streaming
    business: users.business
